### PR TITLE
Project cleanup

### PR DESCRIPTION
**Pull request by JeromSar**
Hey, I've done some cleanup to improve code quality and readability.

Changelist:
* Batch format
* Use braces everywhere
* Add Override annotations where possible
* Organise imports, fields and methods
* POM cleanup
  * Update maven compiler plugin

Most edits have been made with automatic tools, and thus don't contain any problematic changes.

### CODE REVIEW

**Comment by NathanWolf** [comment]
Sure, thank you!

I'm guessing you did this very recently, it looks like all the latest changes are there.

My only hesitation is that the ParticleEffect and ReflectionUtil classes are technically external. Though we've made some changes, I'm a little worried about future merge headaches from a batch-reformat.

Not really sure if the original author of those classes has any intention on updating them, though.

**Comment by NathanWolf** [comment]
Hm- I think this broke all the javadoc block's formatting.

Maybe we could do something a little less drastic? What was your main goal, fixing the whitespace, braces, etc?

**Comment by JeromSar** [comment]
@NathanWolf 
Hey, I've rebased the PR to the latest commit. It should now merge without problems.

To address your questions / issues with this PR:

Although the classes you mentioned are external, they haven't been modified from the original. That means that you could easily replace them, and reformat them without issues. Additionally, I think it's unlikely that they'll be updated anytime soon:
* [ParticleEffect](https://gist.github.com/DarkBlade12/5868517/revisions)'s last edit was early June this year.
* [ReflectionUtils](https://gist.github.com/DarkBlade12/8832875/revisions)'s last edit was December 2015.

As far as I'm aware, this does not break javadoc comments. Instead, they are formatted to match the [Javadoc guidelines](http://www.oracle.com/technetwork/articles/java/index-137868.html). Next to that, with the formatting tools I'm using, it's impossible to format files without formatting javadoc blocks. In my opinion, solely formatting the source wouldn't make sense either.

I'm willing to help with merging this with any future branches, should that become a problem.

My primary intentions for this PR were the following:
  * Fix inconsistency with 4 spaces and tabs. (4 spaces is the standard).
  * Add braces everywhere (consistency)
  * Formatting to improve code quality and avoid inconsistencies for future PR developers (KR & Allman style were both used)\
  * Clean up the POM so it's easier to read.

If you have a problem with any of this, I'll be happy to edit parts of the PR to your liking. :)

**Comment by NathanWolf** [comment]
Thank you for the response! I appreciate the desire for clean code- I'm just generally a little opposed to using an automated mass-reformat hammer. For one thing, it makes tools like "git annotate" become useless.

That said, since this is a shared lib and not really my code to begin with, I'm open to it.

Do you have a way to build the doxygen docs? Looking over the diffs, as I mentioned that was the only thing that looked like it got broke. It's probably not a huge deal, though, there's really only one place where formatting matters- to generate the main front page:

http://jenkins.elmakers.com/job/EffectLib/doxygen/

Essentially embedding indented XML in a javadoc, which is a bit ugly but works.

If that part doesn't break, then I'd be up for pulling this PR.

Alternately, I suppose worse case I can just pull and deal with the consequences.

**Comment by JeromSar** [comment]
@NathanWolf 
Hey,

I only now realize that you're using a different javadoc generation tool. I downloaded doxygen and tried it out to find that indeed javadoc generation was bummed. The latest commit should fix that issue.

Thanks for your patience.

**Comment by NathanWolf** [comment]
Allright, I'll take it! Thank you :)

**Pull request merged**
